# Generated by Django 6.0 on 2026-01-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_l4_config',
            field=models.ForeignKey(blank=True, help_text='Active Level-4 (session) configuration for this project.', limit_choices_to={'level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_using_as_l4', to='config.configrecord'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project', 'ordering'], name='projects_fo_project_9a9eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project', 'parent'], name='projects_fo_project_88407a_idx'),
        ),
    ]
