# Generated by Django 6.0 on 2026-01-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('projects', '0002_project_active_l4_config_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='projects_fo_project_9a9eb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='projects_fo_project_88407a_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='active_l4_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_using_as_active_l4', to='config.configrecord'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project', 'parent', 'ordering'], name='projects_fo_project_3c0d22_idx'),
        ),
    ]
