# Generated by Django 6.0 on 2026-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_folder_projects_fo_project_9a9eb5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('SANDBOX', 'Sandbox')], default='STANDARD', max_length=20),
        ),
    ]
