# Generated by Django 6.0 on 2026-01-12 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('projects', '0004_project_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('PLAN', 'Plan'), ('EXECUTE', 'Execute'), ('REVIEW', 'Review')], default='PLAN', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_type',
            field=models.CharField(choices=[('META', 'Meta / Programme'), ('KNOWLEDGE', 'Knowledge'), ('DELIVERY', 'Delivery'), ('RESEARCH', 'Research'), ('OPERATIONS', 'Operations')], default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_model_ref', models.CharField(blank=True, default='', max_length=255)),
                ('checkpoint_policy_ref', models.CharField(blank=True, default='', max_length=255)),
                ('llm_policy_ref', models.CharField(blank=True, default='', max_length=255)),
                ('language_default', models.CharField(default='en-GB', max_length=20)),
                ('output_format_default', models.CharField(default='code_format', max_length=50)),
                ('user_can_override_language', models.BooleanField(default=True)),
                ('user_can_override_checkpointing', models.BooleanField(default=True)),
                ('user_can_override_output_format', models.BooleanField(default=True)),
                ('user_can_override_templates', models.BooleanField(default=False)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_l1_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_using_as_active_l1', to='config.configrecord')),
                ('active_l2_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_using_as_active_l2', to='config.configrecord')),
                ('active_l3_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_using_as_active_l3', to='config.configrecord')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('field_changes', models.JSONField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('UI', 'UI'), ('API', 'API'), ('MIGRATION', 'Migration'), ('ADMIN', 'Admin')], default='SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'created_at'], name='projects_au_project_92bee2_idx'), models.Index(fields=['actor', 'created_at'], name='projects_au_actor_i_82eb22_idx'), models.Index(fields=['entity_type', 'entity_id'], name='projects_au_entity__1b2a34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CONTRIBUTOR', 'Contributor'), ('OBSERVER', 'Observer')], max_length=20)),
                ('scope_type', models.CharField(choices=[('PROJECT', 'Project'), ('MODULE', 'Module'), ('ARTEFACT', 'Artefact'), ('TAG', 'Tag')], default='PROJECT', max_length=20)),
                ('scope_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left')], default='ACTIVE', max_length=20)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'user'], name='projects_pr_project_710ab3_idx'), models.Index(fields=['project', 'role'], name='projects_pr_project_33946c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('project', 'user', 'role', 'scope_type', 'scope_ref'), name='uniq_active_membership_per_scope'), models.CheckConstraint(condition=models.Q(models.Q(('scope_ref', ''), ('scope_type', 'PROJECT')), ('scope_type__in', ['MODULE', 'ARTEFACT', 'TAG']), _connector='OR'), name='chk_project_scope_ref_blank')],
            },
        ),
        migrations.CreateModel(
            name='UserProjectPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_language', models.CharField(blank=True, default='', max_length=20)),
                ('verbosity', models.CharField(blank=True, default='', max_length=20)),
                ('tone', models.CharField(blank=True, default='', max_length=20)),
                ('formatting', models.CharField(blank=True, default='', max_length=20)),
                ('checkpointing_override', models.CharField(blank=True, default='', max_length=20)),
                ('preferred_outputs', models.JSONField(blank=True, default=list)),
                ('ui_overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_userprefs_per_project')],
            },
        ),
    ]
