# Generated by Django 6.0 on 2026-01-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_mode_project_primary_type_project_purpose_and_more'),
    ]

    operations = [
    ]
