# Generated by Django 6.0.1 on 2026-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_backfill_project_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='chat_read_scope_override',
            field=models.CharField(blank=True, choices=[('OWNER_ONLY', 'Owner only'), ('PROJECT_MANAGERS', 'Project owner + project managers'), ('ANY_MANAGER', 'Org managers (global)')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='projectpolicy',
            name='chat_read_scope_default',
            field=models.CharField(choices=[('OWNER_ONLY', 'Owner only'), ('PROJECT_MANAGERS', 'Project owner + project managers'), ('ANY_MANAGER', 'Org managers (global)')], default='PROJECT_MANAGERS', max_length=30),
        ),
    ]
