# Generated by Django 6.0.1 on 2026-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectmembership_chat_read_scope_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='artefact_root_ref',
            field=models.CharField(blank=True, default='', help_text='Root path for project artefacts under MEDIA_ROOT', max_length=255),
        ),
    ]
