# Generated by Django 6.0.1 on 2026-01-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_default_language_variant'),
        ('projects', '0008_project_artefact_root_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectprefs',
            name='checkpointing_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CHECKPOINTING', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_checkpointing', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprojectprefs',
            name='cognitive_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'COGNITIVE', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_cognitive', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprojectprefs',
            name='epistemic_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'EPISTEMIC', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_epistemic', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprojectprefs',
            name='interaction_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'INTERACTION', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_interaction', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprojectprefs',
            name='performance_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PERFORMANCE', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_performance', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprojectprefs',
            name='presentation_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PRESENTATION', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectprefs_presentation', to='accounts.avatar'),
        ),
    ]
