# Generated by Django 6.0.1 on 2026-01-27 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_userprojectprefs_checkpointing_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDefinitionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('L1-MUST', 'L1-MUST'), ('L1-GOOD', 'L1-GOOD'), ('L1-NICE', 'L1-NICE')], default='L1-MUST', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PROPOSED', 'PROPOSED'), ('PASS_LOCKED', 'PASS_LOCKED')], default='DRAFT', max_length=20)),
                ('value_text', models.TextField(blank=True, default='')),
                ('last_validation', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pde_fields_locked', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pde_fields', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='projects_pr_project_c5271c_idx'), models.Index(fields=['project', 'field_key'], name='projects_pr_project_182449_idx')],
                'unique_together': {('project', 'field_key')},
            },
        ),
    ]
