# Generated by Django 6.0.1 on 2026-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectdefinitionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='definition_status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('SANDBOX', 'Sandbox'), ('DEFINED', 'Defined')], default='UNASSIGNED', max_length=20),
        ),
    ]
