# -*- coding: utf-8 -*-
# projects/migrations/0012_projectpdesnapshot_project_defined_at_and_more.py
# Generated by Django 6.0.1 on 2026-02-03 12:50

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_defined_rows(apps, schema_editor):
    """
    Normalise legacy rows that were marked DEFINED before we introduced defined_cko.
    This must run BEFORE adding the chk_defined_requires_defined_cko constraint.
    """
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(definition_status="DEFINED").update(definition_status="UNASSIGNED")


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_systemconfigpointers_openai_model_default"),
        ("projects", "0011_project_definition_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPDESnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.IntegerField(default=0)),
                ("state", models.CharField(choices=[("OPEN", "Open"), ("COMMITTED", "Committed")], default="OPEN", max_length=20)),
                ("data_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="defined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="defined_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_defined",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pde_revision",
            field=models.IntegerField(
                default=0,
                help_text="Increments whenever a new PDE revision cycle begins.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="definition_status",
            field=models.CharField(
                choices=[("UNASSIGNED", "Unassigned"), ("DRAFT", "Draft"), ("SANDBOX", "Sandbox"), ("DEFINED", "Defined")],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectCKO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.IntegerField(default=1)),
                ("status", models.CharField(
                    choices=[("DRAFT", "Draft"), ("ACCEPTED", "Accepted"), ("SUPERSEDED", "Superseded")],
                    default="DRAFT",
                    max_length=20,
                )),
                ("rel_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="project_ckos_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("project", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="cko_versions",
                    to="projects.project",
                )),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="defined_cko",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the accepted (current) CKO for this project. Non-null iff DEFINED.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_where_defined",
                to="projects.projectcko",
            ),
        ),

        # IMPORTANT: fix legacy rows BEFORE enforcing the invariant.
        migrations.RunPython(fix_defined_rows, migrations.RunPython.noop),

        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("defined_cko__isnull", False), ("definition_status", "DEFINED")),
                    models.Q(("definition_status", "DEFINED"), _negated=True),
                    _connector="OR",
                ),
                name="chk_defined_requires_defined_cko",
            ),
        ),
        migrations.AddField(
            model_name="projectpdesnapshot",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pde_snapshots_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectpdesnapshot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pde_snapshots",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcko",
            index=models.Index(fields=["project", "version"], name="projects_pr_project_e905b6_idx"),
        ),
        migrations.AddIndex(
            model_name="projectcko",
            index=models.Index(fields=["project", "status"], name="projects_pr_project_feb746_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectcko",
            constraint=models.UniqueConstraint(fields=("project", "version"), name="uniq_project_cko_version"),
        ),
        migrations.AddIndex(
            model_name="projectpdesnapshot",
            index=models.Index(fields=["project", "revision"], name="projects_pr_project_9e450b_idx"),
        ),
        migrations.AddIndex(
            model_name="projectpdesnapshot",
            index=models.Index(fields=["project", "state"], name="projects_pr_project_3da38f_idx"),
        ),
    ]
