# Generated by Django 6.0.1 on 2026-02-03 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectpdesnapshot_project_defined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcko',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcko',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_ckos_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcko',
            name='content_text',
            field=models.TextField(blank=True, default='', help_text='Full rendered CKO content at time of commit.'),
        ),
        migrations.AddField(
            model_name='projectcko',
            name='field_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of PDE fields at commit time.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='defined_cko',
            field=models.ForeignKey(blank=True, help_text='Points to the accepted (current) CKO for this project. Non-null iff DEFINED.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_where_defined', to='projects.projectcko'),
        ),
        migrations.AlterField(
            model_name='projectcko',
            name='rel_path',
            field=models.CharField(blank=True, default='', help_text='Relative path under project artefact root.', max_length=255),
        ),
    ]
