# Generated by Django 6.0.1 on 2026-02-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectcko_accepted_at_projectcko_accepted_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_defined_requires_defined_cko',
        ),
        migrations.RemoveField(
            model_name='project',
            name='definition_status',
        ),
    ]
