# Generated by Django 6.0.1 on 2026-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_chk_defined_requires_defined_cko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcko',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='Canonical rendered CKO HTML document.'),
        ),
        migrations.AlterField(
            model_name='projectcko',
            name='content_text',
            field=models.TextField(blank=True, default='', help_text='Plain text shadow of the CKO (export/diff/search).'),
        ),
    ]
