# Generated by Django 6.0.1 on 2026-02-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectcko_content_html_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdefinitionfield',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdefinitionfield',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pde_fields_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdefinitionfield',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdefinitionfield',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pde_fields_proposed', to=settings.AUTH_USER_MODEL),
        ),
    ]
