# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_projectdefinitionfield_last_edited_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPlanningPurpose",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_text", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "DRAFT"), ("PROPOSED", "PROPOSED"), ("PASS_LOCKED", "PASS_LOCKED")], default="DRAFT", max_length=20)),
                ("proposed_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_purpose_locked", to=settings.AUTH_USER_MODEL)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_purpose_edited", to=settings.AUTH_USER_MODEL)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ppde_purpose", to="projects.project")),
                ("proposed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_purpose_proposed", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["project", "status"], name="projects_pr_project_1ddbe2_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProjectPlanningStage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_index", models.IntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("purpose", models.TextField(blank=True, default="")),
                ("entry_condition", models.TextField(blank=True, default="")),
                ("acceptance_statement", models.TextField(blank=True, default="")),
                ("exit_condition", models.TextField(blank=True, default="")),
                ("key_deliverables", models.JSONField(blank=True, default=list)),
                ("duration_estimate", models.TextField(blank=True, default="")),
                ("risks_notes", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "DRAFT"), ("PROPOSED", "PROPOSED"), ("PASS_LOCKED", "PASS_LOCKED")], default="DRAFT", max_length=20)),
                ("proposed_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_stages_locked", to=settings.AUTH_USER_MODEL)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_stages_edited", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ppde_stages", to="projects.project")),
                ("proposed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_stages_proposed", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["order_index", "id"],
                "indexes": [
                    models.Index(fields=["project", "status"], name="projects_pr_project_9e7b9d_idx"),
                    models.Index(fields=["project", "order_index"], name="projects_pr_project_33c2c5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectWKO",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.IntegerField(default=1)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("SUPERSEDED", "Superseded")], default="DRAFT", max_length=20)),
                ("content_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="project_wkos_activated", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_wkos_created", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wko_versions", to="projects.project")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["project", "version"], name="projects_pr_project_3c531f_idx"),
                    models.Index(fields=["project", "status"], name="projects_pr_project_56b084_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectwko",
            constraint=models.UniqueConstraint(fields=("project", "version"), name="uniq_project_wko_version"),
        ),
    ]
