# Generated by Django 6.0.1 on 2026-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_ppde_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectplanningpurpose',
            new_name='projects_pr_project_29e838_idx',
            old_name='projects_pr_project_1ddbe2_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningstage',
            new_name='projects_pr_project_d873fe_idx',
            old_name='projects_pr_project_9e7b9d_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningstage',
            new_name='projects_pr_project_ee4ba1_idx',
            old_name='projects_pr_project_33c2c5_idx',
        ),
        migrations.RenameIndex(
            model_name='projectwko',
            new_name='projects_pr_project_1e81f6_idx',
            old_name='projects_pr_project_3c531f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectwko',
            new_name='projects_pr_project_313bac_idx',
            old_name='projects_pr_project_56b084_idx',
        ),
        migrations.AlterField(
            model_name='projectplanningpurpose',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectplanningstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectwko',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
