# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_rename_projects_pr_project_1ddbe2_idx_projects_pr_project_29e838_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectplanningpurpose",
            name="last_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="projectplanningstage",
            name="last_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="projectwko",
            name="seed_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
