# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_ppde_validation_seed_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ppde_seed_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
