# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_ppde_seed_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseContract",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
                ("purpose_text", models.TextField(blank=True, default="")),
                ("inputs_text", models.TextField(blank=True, default="")),
                ("outputs_text", models.TextField(blank=True, default="")),
                ("method_guidance_text", models.TextField(blank=True, default="")),
                ("acceptance_test_text", models.TextField(blank=True, default="")),
                ("llm_review_prompt_text", models.TextField(blank=True, default="")),
                ("policy_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="phase_contracts_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("key", "version")},
                "indexes": [models.Index(fields=["key", "is_active"], name="projects_ph_key_9a0d6e_idx")],
            },
        ),
    ]
