# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_phase_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectwko",
            name="structure_contract_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="projectwko",
            name="structure_contract_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectwko",
            name="transform_contract_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="projectwko",
            name="transform_contract_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectwko",
            name="change_summary",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
