# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_projectwko_contract_binding"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phasecontract",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="phasecontract",
            constraint=models.UniqueConstraint(fields=("key", "version"), name="uq_phasecontract_key_version"),
        ),
    ]
