# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_phasecontract_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPlanningMilestone",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_index", models.IntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("stage_title", models.CharField(blank=True, default="", max_length=200)),
                ("acceptance_statement", models.TextField(blank=True, default="")),
                ("target_date_hint", models.CharField(blank=True, default="", max_length=100)),
                ("status", models.CharField(choices=[("DRAFT", "DRAFT"), ("PROPOSED", "PROPOSED"), ("PASS_LOCKED", "PASS_LOCKED")], default="DRAFT", max_length=20)),
                ("proposed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_milestones_edited", to=settings.AUTH_USER_MODEL)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_milestones_locked", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ppde_milestones", to="projects.project")),
                ("proposed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_milestones_proposed", to=settings.AUTH_USER_MODEL)),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="milestones", to="projects.projectplanningstage")),
            ],
            options={
                "ordering": ["order_index", "id"],
                "indexes": [
                    models.Index(fields=["project", "status"], name="projects_pr_project_0cd642_idx"),
                    models.Index(fields=["project", "order_index"], name="projects_pr_project_83d15e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectPlanningAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_index", models.IntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("stage_title", models.CharField(blank=True, default="", max_length=200)),
                ("owner_role", models.CharField(blank=True, default="", max_length=120)),
                ("definition_of_done", models.TextField(blank=True, default="")),
                ("effort_hint", models.CharField(blank=True, default="", max_length=120)),
                ("status", models.CharField(choices=[("DRAFT", "DRAFT"), ("PROPOSED", "PROPOSED"), ("PASS_LOCKED", "PASS_LOCKED")], default="DRAFT", max_length=20)),
                ("proposed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_actions_edited", to=settings.AUTH_USER_MODEL)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_actions_locked", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ppde_actions", to="projects.project")),
                ("proposed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_actions_proposed", to=settings.AUTH_USER_MODEL)),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions", to="projects.projectplanningstage")),
            ],
            options={
                "ordering": ["order_index", "id"],
                "indexes": [
                    models.Index(fields=["project", "status"], name="projects_pr_project_8e59e8_idx"),
                    models.Index(fields=["project", "order_index"], name="projects_pr_project_7e7c6e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectPlanningRisk",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_index", models.IntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("stage_title", models.CharField(blank=True, default="", max_length=200)),
                ("probability", models.CharField(blank=True, default="", max_length=10)),
                ("impact", models.CharField(blank=True, default="", max_length=10)),
                ("mitigation", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "DRAFT"), ("PROPOSED", "PROPOSED"), ("PASS_LOCKED", "PASS_LOCKED")], default="DRAFT", max_length=20)),
                ("proposed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_risks_edited", to=settings.AUTH_USER_MODEL)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_risks_locked", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ppde_risks", to="projects.project")),
                ("proposed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ppde_risks_proposed", to=settings.AUTH_USER_MODEL)),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="risks", to="projects.projectplanningstage")),
            ],
            options={
                "ordering": ["order_index", "id"],
                "indexes": [
                    models.Index(fields=["project", "status"], name="projects_pr_project_1a1c6e_idx"),
                    models.Index(fields=["project", "order_index"], name="projects_pr_project_9e8c7a_idx"),
                ],
            },
        ),
    ]
