# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_ppde_plan_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExecutionTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("stage_title", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(choices=[("TODO", "TODO"), ("IN_PROGRESS", "IN_PROGRESS"), ("BLOCKED", "BLOCKED"), ("DONE", "DONE")], default="TODO", max_length=20)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("source_wko_version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="execution_tasks", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_tasks", to="projects.project")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["project", "stage_title"], name="projects_pr_project_6d912f_idx"),
                    models.Index(fields=["project", "status"], name="projects_pr_project_4b8c95_idx"),
                    models.Index(fields=["project", "source_wko_version"], name="projects_pr_project_0a5f2d_idx"),
                ],
            },
        ),
    ]
