# Generated by Django 6.0.1 on 2026-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_execution_tasks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phasecontract',
            new_name='projects_ph_key_d50b15_idx',
            old_name='projects_ph_key_9a0d6e_idx',
        ),
        migrations.RenameIndex(
            model_name='projectexecutiontask',
            new_name='projects_pr_project_45d78a_idx',
            old_name='projects_pr_project_6d912f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectexecutiontask',
            new_name='projects_pr_project_63a721_idx',
            old_name='projects_pr_project_4b8c95_idx',
        ),
        migrations.RenameIndex(
            model_name='projectexecutiontask',
            new_name='projects_pr_project_edf7a6_idx',
            old_name='projects_pr_project_0a5f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningaction',
            new_name='projects_pr_project_f31cd8_idx',
            old_name='projects_pr_project_8e59e8_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningaction',
            new_name='projects_pr_project_d2b3c1_idx',
            old_name='projects_pr_project_7e7c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningmilestone',
            new_name='projects_pr_project_6401d5_idx',
            old_name='projects_pr_project_0cd642_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningmilestone',
            new_name='projects_pr_project_a2bf7f_idx',
            old_name='projects_pr_project_83d15e_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningrisk',
            new_name='projects_pr_project_30fb2b_idx',
            old_name='projects_pr_project_1a1c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplanningrisk',
            new_name='projects_pr_project_457dd0_idx',
            old_name='projects_pr_project_9e8c7a_idx',
        ),
        migrations.AlterField(
            model_name='phasecontract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectexecutiontask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectplanningaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectplanningmilestone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectplanningrisk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
