# -*- coding: utf-8 -*-
# Generated by Codex on 2026-02-06
from __future__ import annotations

from django.db import migrations


def _seed_contracts(apps, schema_editor) -> None:
    PhaseContract = apps.get_model("projects", "PhaseContract")

    seeds = [
        {
            "key": "STRUCTURE_PROJECT",
            "title": "PPDE Contract - Structure Project (CKO to Stage Map)",
            "version": 1,
            "is_active": True,
            "purpose_text": (
                "Produce a practical stage map from the accepted CKO. "
                "The stage map must be suitable for PPDE refinement and later planning."
            ),
            "inputs_text": (
                "Accepted CKO snapshot (fields as available).\n"
                "Seed summary if present.\n"
                "Project constraints from the accepted CKO.\n"
                "Optional prior PPDE working draft context (read-only)."
            ),
            "outputs_text": (
                "JSON only: {\"stages\":[...]} matching the stage-map schema.\n"
                "3 to 8 stages preferred.\n"
                "Each stage includes title, description, purpose, entry_condition, "
                "acceptance_statement, exit_condition, key_deliverables, "
                "duration_estimate, risks_notes."
            ),
            "method_guidance_text": (
                "Derive stages top-down from the CKO goal and acceptance test.\n"
                "Make stages non-overlapping and sequential where sensible.\n"
                "Keep each stage concrete.\n"
                "Entry condition: what must be true to start.\n"
                "Acceptance statement: verifiable completion statement.\n"
                "Exit condition: what is true when leaving the stage.\n"
                "Use language that a small team can execute.\n"
                "If the CKO is vague, make reasonable assumptions and record them in risks_notes."
            ),
            "acceptance_test_text": (
                "Output is valid JSON only and matches schema.\n"
                "Every stage has a non-empty title and acceptance_statement.\n"
                "key_deliverables has at least one item per stage.\n"
                "Stages are not duplicates and do not substantially overlap.\n"
                "Stages collectively cover the project from start to finish."
            ),
            "llm_review_prompt_text": (
                "Check the stage map for overlap, gaps, and unverifiable acceptance statements.\n"
                "Ensure each stage is concrete and contains at least one deliverable.\n"
                "If any stage is too vague, rewrite it to be executable."
            ),
            "policy_json": {
                "output_format": "json_only",
                "preferred_stage_count_min": 3,
                "preferred_stage_count_max": 8,
                "require_non_overlapping_stages": True,
                "require_verifiable_acceptance": True,
                "require_key_deliverables_min": 1,
                "tone": "brief_executable",
                "notes": "Used for committer-only stage-map generation from accepted CKO.",
            },
        },
        {
            "key": "TRANSFORM_STAGE",
            "title": "PPDE Contract - Transform Stage (Refine and Verify)",
            "version": 1,
            "is_active": True,
            "purpose_text": (
                "Improve a single stage so it is clear, testable, and executable. "
                "Produce stage text that supports downstream planning."
            ),
            "inputs_text": (
                "Current stage object (all stage fields).\n"
                "Neighbouring stage titles if available.\n"
                "Project planning purpose text.\n"
                "Project constraints from accepted CKO or seed summary."
            ),
            "outputs_text": (
                "JSON only: a single stage object with the same keys as the stage schema.\n"
                "Fields may be revised for clarity but intent must be preserved."
            ),
            "method_guidance_text": (
                "Make acceptance_statement verifiable.\n"
                "Ensure entry_condition and exit_condition are concrete and distinct.\n"
                "Ensure key_deliverables are tangible outcomes, not vague activities.\n"
                "Keep description concise; move uncertainty into risks_notes.\n"
                "Avoid overlap with neighbouring stages where context is available.\n"
                "Prefer plain language; avoid jargon."
            ),
            "acceptance_test_text": (
                "Output is valid JSON only and matches the stage schema.\n"
                "title and acceptance_statement are non-empty.\n"
                "key_deliverables contains at least one non-empty string.\n"
                "entry_condition, acceptance_statement, and exit_condition are not redundant.\n"
                "The stage is executable by a team without extra interpretation."
            ),
            "llm_review_prompt_text": (
                "Review the revised stage for unverifiable acceptance statements, "
                "vague deliverables, overlap with other stages, and missing risks.\n"
                "Rewrite weak parts to be concrete and testable."
            ),
            "policy_json": {
                "output_format": "json_only",
                "require_verifiable_acceptance": True,
                "require_key_deliverables_min": 1,
                "allow_boundary_adjustment": True,
                "tone": "brief_executable",
                "notes": "Used for per-stage verify and contributor propose-lock workflow.",
            },
        },
    ]

    for seed in seeds:
        PhaseContract.objects.filter(key=seed["key"]).update(is_active=False)
        obj, created = PhaseContract.objects.get_or_create(
            key=seed["key"],
            version=seed["version"],
            defaults=seed,
        )
        if not created:
            for field, value in seed.items():
                setattr(obj, field, value)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_rename_projects_ph_key_9a0d6e_idx_projects_ph_key_d50b15_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(_seed_contracts, migrations.RunPython.noop),
    ]
