# Generated by Django 6.0.1 on 2026-02-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_chatworkspace_last_answer_at_and_more'),
        ('projects', '0027_seed_phase_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTopicChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=16)),
                ('topic_key', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_binding', to='chats.chatworkspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_chats', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'user'], name='projects_pr_project_ca901d_idx'), models.Index(fields=['project', 'scope', 'topic_key'], name='projects_pr_project_fe07df_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'scope', 'topic_key'), name='uq_project_topic_chat')],
            },
        ),
    ]
