# Generated by Django 6.0.1 on 2026-02-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectpdo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectpdo',
            new_name='projects_pr_project_ea4681_idx',
            old_name='projects_pr_project_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='projectpdo',
            new_name='projects_pr_project_f383b2_idx',
            old_name='projects_pr_project_4d5e6f_idx',
        ),
    ]
