# Generated by Django 6.0.1 on 2026-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_rename_projects_pr_project_1a2b3c_idx_projects_pr_project_ea4681_idx_and_more'),
        ('projects', '0037_remove_old_stage_fields'),
    ]

    operations = [
    ]
