# Generated by Django 6.0.1 on 2026-02-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_project_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectanchor',
            new_name='projects_pr_project_03aedb_idx',
            old_name='projects_anchor_project_marker_idx',
        ),
        migrations.RenameIndex(
            model_name='projectreviewchat',
            new_name='projects_pr_project_0082cc_idx',
            old_name='projects_review_project_user_marker_idx',
        ),
    ]
