# Generated by Django 6.0.1 on 2026-02-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_add_anchor_json_tko_pko'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectpko',
            new_name='projects_pr_project_4605c6_idx',
            old_name='projects_pr_project_83e8f3_idx',
        ),
        migrations.RenameIndex(
            model_name='projectpko',
            new_name='projects_pr_project_c839b8_idx',
            old_name='projects_pr_project_2f6b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttko',
            new_name='projects_pr_project_9ce5b8_idx',
            old_name='projects_pr_project_3c1b54_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttko',
            new_name='projects_pr_project_219039_idx',
            old_name='projects_pr_project_5dcb8f_idx',
        ),
    ]
