# Generated by Django 6.0.1 on 2026-02-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_rename_projects_pr_project_83e8f3_idx_projects_pr_project_4605c6_idx_and_more'),
        ('projects', '0042_update_project_anchor_status'),
    ]

    operations = [
    ]
