# Generated by Django 6.0.1 on 2026-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_add_project_review_stage_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreviewstagechat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
