# Generated by Django 6.0.1 on 2026-02-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_alter_projectreviewstagechat_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAnchorAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marker", models.CharField(choices=[("INTENT", "Intent"), ("ROUTE", "Route"), ("EXECUTE", "Execute"), ("COMPLETE", "Complete")], max_length=16)),
                ("change_type", models.CharField(choices=[("UPDATE", "Update"), ("STATUS", "Status"), ("RESEED", "Reseed")], default="UPDATE", max_length=16)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("status_before", models.CharField(blank=True, default="", max_length=16)),
                ("status_after", models.CharField(blank=True, default="", max_length=16)),
                ("before_content", models.TextField(blank=True, default="")),
                ("after_content", models.TextField(blank=True, default="")),
                ("before_content_json", models.JSONField(blank=True, default=dict)),
                ("after_content_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("anchor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_rows", to="projects.projectanchor")),
                ("changed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_anchor_audits", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="anchor_audits", to="projects.project")),
            ],
        ),
        migrations.AddIndex(
            model_name="projectanchoraudit",
            index=models.Index(fields=["project", "marker", "created_at"], name="projects_pr_project_4ef8f9_idx"),
        ),
        migrations.AddIndex(
            model_name="projectanchoraudit",
            index=models.Index(fields=["project", "created_at"], name="projects_pr_project_3e6963_idx"),
        ),
    ]
