# Generated by Django 6.0.1 on 2026-02-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_projectanchoraudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectanchoraudit',
            new_name='projects_pr_project_0b8ca9_idx',
            old_name='projects_pr_project_4ef8f9_idx',
        ),
        migrations.RenameIndex(
            model_name='projectanchoraudit',
            new_name='projects_pr_project_63ccb5_idx',
            old_name='projects_pr_project_3e6963_idx',
        ),
    ]
