# Generated by Django 6.0.1 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_rename_projects_pr_project_4ef8f9_idx_projects_pr_project_0b8ca9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="planning_mode",
            field=models.CharField(
                choices=[("ASSISTED", "Assisted"), ("AUTO", "Auto")],
                default="ASSISTED",
                max_length=16,
            ),
        ),
    ]
