# Generated by Django 6.0.1 on 2026-02-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_projectmembership_planning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boundary_profile_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'updated_at'], name='projects_po_project_51aa92_idx')],
            },
        ),
    ]
