# Generated by Django 6.0.1 on 2026-02-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_projectdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="NEW", max_length=40)),
                ("active_phase", models.CharField(blank=True, default="", max_length=80)),
                ("seed_log", models.JSONField(blank=True, default=list)),
                ("active_seed_revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_items", to="projects.project")),
            ],
            options={
                "indexes": [models.Index(fields=["project", "updated_at"], name="projects_wo_project_224d14_idx")],
            },
        ),
    ]
