# Generated by Django 6.0.1 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_workitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="deliverables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

