# Generated by Django 6.0.1 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_workitem_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="boundary_profile_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

