# Generated by Django 6.0.1 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_workitem_boundary_profile_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="intent_raw",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workitem",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]

