# Generated by Django 6.0.1 on 2026-02-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_workitem_phase_seed_to_refine'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_mode',
            field=models.CharField(choices=[('PDE', 'PDE'), ('DERAX_WORK', 'DERAX work')], default='PDE', max_length=20),
        ),
        migrations.AddField(
            model_name='workitem',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('project',), name='uq_workitem_primary_per_project'),
        ),
    ]
