# Generated by Django 5.2.5 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0057_project_workflow_mode_workitem_is_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="derax_endpoint_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workitem",
            name="derax_endpoint_spec",
            field=models.TextField(blank=True, default=""),
        ),
    ]
