# Generated by Django 5.2.5 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0058_workitem_derax_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="derax_define_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
