# Generated by Django 5.2.5 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0060_workitem_derax_explore_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="derax_runs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
