# Generated by Django 6.0 on 2026-01-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='project_id',
            new_name='legacy_project_id',
        ),
        migrations.AddField(
            model_name='userrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='projects.project'),
        ),
    ]
