# Generated by Django 6.0 on 2026-01-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_project_id_userrole_legacy_project_id_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'scope_type', 'project')},
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='legacy_project_id',
        ),
    ]
