# Generated by Django 6.0 on 2026-01-08 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COGNITIVE', 'Cognitive'), ('INTERACTION', 'Interaction'), ('PRESENTATION', 'Presentation'), ('EPISTEMIC', 'Epistemic'), ('PERFORMANCE', 'Performance'), ('CHECKPOINTING', 'Checkpointing')], max_length=20)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'is_active'], name='accounts_av_categor_36f96f_idx'), models.Index(fields=['category', 'key'], name='accounts_av_categor_9d1778_idx')],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='English', max_length=40)),
                ('default_language_variant', models.CharField(choices=[('en-gb', 'British English'), ('en-us', 'American English')], default='en-gb', max_length=10)),
                ('language_switching_permitted', models.BooleanField(default=True)),
                ('persist_language_switch_for_session', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpointing_avatar', models.ForeignKey(limit_choices_to={'category': 'CHECKPOINTING', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_checkpointing', to='accounts.avatar')),
                ('cognitive_avatar', models.ForeignKey(limit_choices_to={'category': 'COGNITIVE', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_cognitive', to='accounts.avatar')),
                ('epistemic_avatar', models.ForeignKey(limit_choices_to={'category': 'EPISTEMIC', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_epistemic', to='accounts.avatar')),
                ('interaction_avatar', models.ForeignKey(limit_choices_to={'category': 'INTERACTION', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_interaction', to='accounts.avatar')),
                ('performance_avatar', models.ForeignKey(limit_choices_to={'category': 'PERFORMANCE', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_performance', to='accounts.avatar')),
                ('presentation_avatar', models.ForeignKey(limit_choices_to={'category': 'PRESENTATION', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='users_presentation', to='accounts.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['default_language_variant'], name='accounts_us_default_1f1af3_idx')],
            },
        ),
    ]
