# Generated by Django 6.0 on 2026-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_avatar_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_language_variant',
            field=models.CharField(default='British English', max_length=40),
        ),
    ]
