# Generated by Django 6.0.1 on 2026-01-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_default_language_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approach_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'APPROACH', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_approach', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='control_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CONTROL', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_control', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reasoning_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'REASONING', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_reasoning', to='accounts.avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tone_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TONE', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_tone', to='accounts.avatar'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='category',
            field=models.CharField(choices=[('COGNITIVE', 'Cognitive'), ('INTERACTION', 'Interaction'), ('PRESENTATION', 'Presentation'), ('EPISTEMIC', 'Epistemic'), ('PERFORMANCE', 'Performance'), ('CHECKPOINTING', 'Checkpointing'), ('TONE', 'Tone'), ('REASONING', 'Reasoning'), ('APPROACH', 'Approach'), ('CONTROL', 'Control')], max_length=20),
        ),
    ]
