# Generated by Django 6.0.1 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_llm_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="llm_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic"), ("copilot", "Copilot")],
                default="openai",
                max_length=20,
            ),
        ),
    ]
