# Generated by Django 6.0.1 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userprofile_llm_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="anthropic_model_default",
            field=models.CharField(blank=True, default="claude-sonnet-4-5-20250929", max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="openai_model_default",
            field=models.CharField(blank=True, default="gpt-5.1", max_length=80),
        ),
    ]
