# Generated by Django 6.0.1 on 2026-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_openai_model_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summary_rollup_trigger_message_count',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
