# Generated by Django 6.0.1 on 2026-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_summary_rollup_trigger_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deepseek_model_default',
            field=models.CharField(blank=True, default='deepseek-chat', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('copilot', 'Copilot')], default='openai', max_length=20),
        ),
    ]
