# Generated by Django 6.0.1 on 2026-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_deepseek_model_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_model_default',
            field=models.CharField(blank=True, default='gemini-2.5-flash', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('copilot', 'Copilot')], default='openai', max_length=20),
        ),
    ]
