# Generated by Django 6.0.1 on 2026-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_gemini_model_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='openai_model_default',
            field=models.CharField(blank=True, default='gpt-5.5', max_length=80),
        ),
    ]
