# Generated by Django 6.0.1 on 2026-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_openai_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_model_default',
            field=models.CharField(blank=True, default='gemini-3.5-flash', max_length=80),
        ),
    ]
