# Generated by Django 6.0 on 2026-01-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('ORG', 'Organisation'), ('PROJECT', 'Project'), ('USER', 'User'), ('SESSION', 'Session')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')])),
                ('file_id', models.CharField(max_length=120)),
                ('file_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='config.configscope')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0.0', max_length=30)),
                ('content_text', models.TextField()),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config.configrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='configscope',
            index=models.Index(fields=['scope_type'], name='config_conf_scope_t_37a156_idx'),
        ),
        migrations.AddIndex(
            model_name='configscope',
            index=models.Index(fields=['project'], name='config_conf_project_e39f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='configscope',
            index=models.Index(fields=['user'], name='config_conf_user_id_cb3663_idx'),
        ),
        migrations.AddIndex(
            model_name='configrecord',
            index=models.Index(fields=['level', 'status'], name='config_conf_level_d8d127_idx'),
        ),
        migrations.AddIndex(
            model_name='configrecord',
            index=models.Index(fields=['file_id'], name='config_conf_file_id_9ecf51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configrecord',
            unique_together={('level', 'file_id', 'scope')},
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['config', 'created_at'], name='config_conf_config__e551ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configversion',
            unique_together={('config', 'version')},
        ),
    ]
