# Generated by Django 6.0.1 on 2026-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrecord',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Human-readable name shown in the UI', max_length=255),
        ),
    ]
