# Generated by Django 6.0.1 on 2026-01-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_configrecord_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfigPointers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_l1_config', models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config.configrecord')),
                ('active_l2_config', models.ForeignKey(blank=True, limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config.configrecord')),
                ('active_l3_config', models.ForeignKey(blank=True, limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config.configrecord')),
                ('active_l4_config', models.ForeignKey(blank=True, limit_choices_to={'level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config.configrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_config_pointer_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System config pointers',
                'verbose_name_plural': 'System config pointers',
            },
        ),
    ]
