# Generated by Django 6.0.1 on 2026-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_systemconfigpointers'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfigpointers',
            name='openai_model_default',
            field=models.CharField(blank=True, default='gpt-5.1', help_text='Default OpenAI model key, e.g. gpt-5.1, gpt-4.1-mini, o4-mini', max_length=80),
        ),
    ]
