# Generated by Django 6.0.1 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_systemconfigpointers_openai_model_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfigpointers",
            name="anthropic_model_default",
            field=models.CharField(
                blank=True,
                default="claude-sonnet-4-5-20250929",
                help_text=(
                    "Default Anthropic model key, e.g. claude-sonnet-4-5-20250929, "
                    "claude-opus-4-5-20251101, claude-haiku-4-5-20251001"
                ),
                max_length=80,
            ),
        ),
    ]
