# Generated by Django 6.0.1 on 2026-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_systemconfigpointers_anthropic_model_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfigpointers',
            name='gemini_model_default',
            field=models.CharField(blank=True, default='gemini-2.5-flash', help_text='Default Gemini model key, e.g. gemini-2.5-pro, gemini-2.5-flash, gemini-2.5-flash-lite', max_length=80),
        ),
    ]
