# Generated by Django 6.0.1 on 2026-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_systemconfigpointers_gemini_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfigpointers',
            name='openai_model_default',
            field=models.CharField(blank=True, default='gpt-5.5', help_text='Default OpenAI model key, e.g. gpt-5.5, gpt-4.1-mini, o4-mini', max_length=80),
        ),
    ]
