# Generated by Django 6.0.1 on 2026-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_systemconfigpointers_openai_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfigpointers',
            name='gemini_model_default',
            field=models.CharField(blank=True, default='gemini-3.5-flash', help_text='Default Gemini model key, e.g. gemini-2.5-pro, gemini-3.5-flash, gemini-2.5-flash', max_length=80),
        ),
    ]
