# Generated by Django 6.0 on 2026-01-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('CKO', 'Canonical Knowledge Object'), ('WKO', 'Workflow Knowledge Object'), ('DKO', 'Derived Knowledge Object'), ('TKO', 'Transitional Knowledge Object'), ('PKO', 'Personal Knowledge Object')], max_length=10)),
                ('local_id', models.CharField(blank=True, max_length=120)),
                ('official_id', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('canonical_summary', models.CharField(blank=True, max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('scope_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('ACCEPTED', 'Accepted'), ('CONTESTED', 'Contested'), ('REJECTED_REWORK', 'Rejected: Rework'), ('REJECTED_CLOSED', 'Rejected: Closed'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('CLOSED', 'Closed')], default='CANDIDATE', max_length=30)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_objects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('REFERENCES', 'References'), ('DERIVED_FROM', 'Derived from'), ('SUPERSEDES', 'Supersedes'), ('SUPERSEDED_BY', 'Superseded by'), ('DISPUTES', 'Disputes'), ('IMPLEMENTS', 'Implements')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='objects.knowledgeobject')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='objects.knowledgeobject')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeObjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('content_text', models.TextField()),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='objects.knowledgeobject')),
            ],
        ),
    ]
