# Generated by Django 6.0 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.CharField(choices=[('ANSWER', 'Answer'), ('COMMENTARY', 'Commentary'), ('ANALYSIS', 'Analysis'), ('REASONING', 'Reasoning'), ('SOURCES', 'Sources'), ('VISUALS', 'Visuals'), ('META', 'Meta')], default='ANSWER', max_length=20),
        ),
    ]
