# Generated by Django 6.0 on 2026-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatmessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='resolved_context',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
