# Generated by Django 6.0 on 2026-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatworkspace_resolved_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='last_output_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='last_output_snippet',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='chatworkspace',
            name='resolved_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
