# Generated by Django 6.0.1 on 2026-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatworkspace_last_output_at_and_more'),
        ('objects', '0002_knowledgeobject_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='raw_text',
        ),
        migrations.RenameField(
            model_name='chatworkspace',
            old_name='resolved_context',
            new_name='chat_overrides',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='tool_metadata',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reasoning_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='segment_meta',
            field=models.JSONField(blank=True, default=dict, help_text='parser_version, confidence, extraction notes'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Monotonic per-chat ordering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='object_refs',
            field=models.ManyToManyField(blank=True, related_name='source_messages', to='objects.knowledgeobject'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'sequence'], name='chats_chatm_chat_id_eaff58_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='chats_chatm_chat_id_454977_idx'),
        ),
        # migrations.AddConstraint(
        #     model_name='chatmessage',
        #     constraint=models.UniqueConstraint(fields=('chat', 'sequence'), name='uniq_message_sequence_per_chat'),
        # ),
    ]
