# Generated by Django 6.0.1 on 2026-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_backfill_chatmessage_sequence'),
        ('objects', '0002_knowledgeobject_approved_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('chat', 'sequence'), name='uniq_message_sequence_per_chat'),
        ),
    ]
