# Generated by Django 6.0.1 on 2026-01-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chatmessage_uniq_message_sequence_per_chat'),
        ('projects', '0007_projectmembership_chat_read_scope_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_ref', models.JSONField()),
                ('l2_ref', models.JSONField()),
                ('l3_ref', models.JSONField()),
                ('user_prefs_ref', models.JSONField()),
                ('overrides_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='chats.chatworkspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_snapshots', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat',), name='uniq_snapshot_per_chat')],
            },
        ),
    ]
