# Generated by Django 6.0.1 on 2026-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chatsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='constraints_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='goal_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='is_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='non_goals_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='success_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
