# Generated by Django 6.0.1 on 2026-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chatworkspace_constraints_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='cde_is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
