# Generated by Django 6.0.1 on 2026-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_chatworkspace_cde_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='cde_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
