# Generated by Django 6.0.1 on 2026-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_chatworkspace_cde_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='last_answer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatworkspace',
            name='last_answer_snippet',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
