# Generated by Django 6.0.1 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0012_chatworkspace_last_answer_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="importance",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("PINNED", "Pinned"), ("IGNORE", "Ignore")],
                db_index=True,
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatworkspace",
            name="pinned_conclusion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatworkspace",
            name="pinned_cursor_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatworkspace",
            name="pinned_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatworkspace",
            name="pinned_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
