# Generated by Django 6.0.1 on 2026-02-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0013_chatmessage_importance_and_chatworkspace_pinning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRollupEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.CharField(choices=[("AUTO", "Auto"), ("PIN", "Pin")], default="AUTO", max_length=16)),
                ("prev_summary", models.TextField(blank=True, default="")),
                ("prev_conclusion", models.TextField(blank=True, default="")),
                ("prev_cursor_message_id", models.BigIntegerField(blank=True, null=True)),
                ("new_summary", models.TextField(blank=True, default="")),
                ("new_conclusion", models.TextField(blank=True, default="")),
                ("new_cursor_message_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rollup_events", to="chats.chatworkspace")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_rollup_events_created", to=settings.AUTH_USER_MODEL)),
                ("reverted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_rollup_events_reverted", to=settings.AUTH_USER_MODEL)),
                ("trigger_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rollup_triggers", to="chats.chatmessage")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["chat", "created_at"], name="chats_chatr_chat_id_5ebfd8_idx"),
                    models.Index(fields=["chat", "reverted_at"], name="chats_chatr_chat_id_dc7056_idx"),
                ],
            },
        ),
    ]
