# Generated by Django 6.0.1 on 2026-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_chatrollupevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkspace',
            name='boundary_profile_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
