# Generated by Django 5.2.5 on 2026-02-23 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0015_chatworkspace_boundary_profile_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120, unique=True)),
                ("scope_type", models.CharField(choices=[("GLOBAL", "Global")], default="GLOBAL", max_length=20)),
                ("scope_id", models.IntegerField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("override_text", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_overrides_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["key"], name="chats_contr_key_6dce99_idx"), models.Index(fields=["scope_type", "scope_id"], name="chats_contr_scope_t_ee917d_idx")],
            },
        ),
    ]
