# Generated by Django 6.0.1 on 2026-02-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_contractoverride'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractoverride',
            new_name='chats_contr_key_84e434_idx',
            old_name='chats_contr_key_6dce99_idx',
        ),
        migrations.RenameIndex(
            model_name='contractoverride',
            new_name='chats_contr_scope_t_e9da5a_idx',
            old_name='chats_contr_scope_t_ee917d_idx',
        ),
    ]
