# Generated by Django 6.0.1 on 2026-02-23 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_rename_chats_contr_key_6dce99_idx_chats_contr_key_84e434_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('scope_type', models.CharField(choices=[('GLOBAL_DEFAULT', 'Global default'), ('USER', 'User')], max_length=20)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_texts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'scope_type', 'scope_id'], name='chats_contr_key_5d190b_idx'), models.Index(fields=['scope_type', 'scope_id', 'status'], name='chats_contr_scope_t_e0621a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'GLOBAL_DEFAULT'), ('scope_id__isnull', True)), models.Q(('scope_type', 'USER'), ('scope_id__isnull', False)), _connector='OR'), name='ck_contracttext_scope_shape'), models.UniqueConstraint(condition=models.Q(('scope_id__isnull', False), ('status', 'ACTIVE')), fields=('key', 'scope_type', 'scope_id'), name='uq_contracttext_active_scoped'), models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True), ('status', 'ACTIVE')), fields=('key', 'scope_type'), name='uq_contracttext_active_global')],
            },
        ),
    ]
