# Generated by Django 6.0.1 on 2026-02-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0018_contracttext"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatworkspace",
            name="derax_enabled",
            field=models.BooleanField(default=False),
        ),
    ]

