# Generated by Django 6.0 on 2026-01-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('objects', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigatorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('workflow_ref', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigator_runs', to='chats.chatworkspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigator_runs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='InvocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment', models.CharField(choices=[('COMP-PRIMARY', 'Primary'), ('COMP-ANALYSIS', 'Analysis'), ('COMP-REASONING', 'Reasoning'), ('COMP-SUMMARY', 'Summary')], default='COMP-PRIMARY', max_length=20)),
                ('backend', models.CharField(blank=True, max_length=50)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('output_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='navigator.navigatorrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'created_at'], name='navigator_i_run_id_26bb98_idx'), models.Index(fields=['compartment'], name='navigator_i_compart_227f36_idx'), models.Index(fields=['backend'], name='navigator_i_backend_e3e539_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('routed_compartment', models.CharField(max_length=20)),
                ('policy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='navigator.navigatorrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'created_at'], name='navigator_r_run_id_5af43e_idx'), models.Index(fields=['channel'], name='navigator_r_channel_5bafbc_idx'), models.Index(fields=['routed_compartment'], name='navigator_r_routed__bd8fb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_compartment', models.CharField(max_length=20)),
                ('to_compartment', models.CharField(max_length=20)),
                ('transfer_type', models.CharField(choices=[('VIEW', 'View'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=10)),
                ('classification', models.CharField(default='INTERNAL', max_length=20)),
                ('content_ref', models.CharField(blank=True, max_length=200)),
                ('rationale', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL)),
                ('obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.knowledgeobject')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to='navigator.navigatorrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'created_at'], name='navigator_t_run_id_d69098_idx'), models.Index(fields=['transfer_type'], name='navigator_t_transfe_e545bc_idx'), models.Index(fields=['classification'], name='navigator_t_classif_32fe2a_idx')],
            },
        ),
    ]
