# -*- coding: utf-8 -*-

from __future__ import annotations


CONTRACT_KEYS = [
    {
        "key": "envelope.json_schema",
        "label": "Core JSON envelope",
        "type": "ENVELOPE",
        "source_hint": "STATIC",
        "builder_ref": "chats.services.contracts.pipeline.build_envelope_block",
    },
    {
        "key": "avatars.protocol.0",
        "label": "Language protocol",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "avatars.protocol.1",
        "label": "Tone protocol",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "avatars.protocol.2",
        "label": "Reasoning protocol",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "avatars.protocol.3",
        "label": "Approach protocol",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "avatars.protocol.4",
        "label": "Control protocol",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "avatars.protocol.5",
        "label": "Active avatars summary",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "boundary.effective",
        "label": "Effective boundary contract",
        "type": "BOUNDARY",
        "source_hint": "GENERATED",
        "builder_ref": "chats.services.contracts.boundary_resolver.resolve_boundary_contract",
    },
    {
        "key": "boundary.profile",
        "label": "Boundary profile (structured)",
        "type": "BOUNDARY",
        "source_hint": "GENERATED",
        "builder_ref": "work_item/project/chat boundary_profile_json",
    },
    {
        "key": "phase.contract",
        "label": "Effective phase contract",
        "type": "PHASE",
        "source_hint": "GENERATED",
        "builder_ref": "chats.services.contracts.phase_resolver.resolve_phase_contract",
    },
    {
        "key": "active_avatars",
        "label": "Active avatars summary",
        "type": "AVATAR",
        "source_hint": "GENERATED",
        "builder_ref": "projects.services.llm_instructions.build_system_messages",
    },
    {
        "key": "phase.define",
        "label": "Phase contract: DEFINE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['DEFINE']",
    },
    {
        "key": "phase.explore",
        "label": "Phase contract: EXPLORE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['EXPLORE']",
    },
    {
        "key": "phase.refine",
        "label": "Phase contract: REFINE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['REFINE']",
    },
    {
        "key": "phase.approve",
        "label": "Phase contract: APPROVE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['APPROVE']",
    },
    {
        "key": "phase.execute",
        "label": "Phase contract: EXECUTE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['EXECUTE']",
    },
    {
        "key": "phase.complete",
        "label": "Phase contract: COMPLETE",
        "type": "PHASE",
        "source_hint": "STATIC",
        "builder_ref": "projects.phase_contracts.PHASE_CONTRACTS['COMPLETE']",
    },
    {
        "key": "cde.contract.0",
        "label": "CDE contract block",
        "type": "CDE",
        "source_hint": "GENERATED",
        "builder_ref": "chats.services.cde_injection.build_cde_system_blocks",
    },
    {
        "key": "cde.contract",
        "label": "CDE contract (effective)",
        "type": "CDE",
        "source_hint": "GENERATED",
        "builder_ref": "chats.services.cde_injection.build_cde_system_blocks",
    },
    {
        "key": "cde.validator.boilerplate",
        "label": "CDE validator boilerplate",
        "type": "CDE",
        "source_hint": "STATIC",
        "builder_ref": "chats.services.cde.CDE_VALIDATOR_BOILERPLATE",
    },
    {
        "key": "cde.draft.boilerplate",
        "label": "CDE draft boilerplate",
        "type": "CDE",
        "source_hint": "STATIC",
        "builder_ref": "chats.services.cde.CDE_DRAFT_BOILERPLATE",
    },
    {
        "key": "pde.validator",
        "label": "PDE validator boilerplate",
        "type": "PDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.services.pde.PDE_VALIDATOR_BOILERPLATE",
    },
    {
        "key": "pde.validator.boilerplate",
        "label": "PDE validator boilerplate",
        "type": "PDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.services.pde.PDE_VALIDATOR_BOILERPLATE",
    },
    {
        "key": "pde.draft",
        "label": "PDE draft boilerplate",
        "type": "PDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.services.pde.PDE_DRAFT_BOILERPLATE",
    },
    {
        "key": "pde.draft.boilerplate",
        "label": "PDE draft boilerplate",
        "type": "PDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.services.pde.PDE_DRAFT_BOILERPLATE",
    },
    {
        "key": "ppde.validator",
        "label": "PPDE validator boilerplate",
        "type": "PPDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_ppde_ui.PPDE_VALIDATOR_BOILERPLATE",
    },
    {
        "key": "ppde.seed_summary",
        "label": "PPDE seed summary boilerplate",
        "type": "PPDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_ppde_ui.PPDE_SEED_SUMMARY_BOILERPLATE",
    },
    {
        "key": "ppde.seed_purpose",
        "label": "PPDE seed purpose boilerplate",
        "type": "PPDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_ppde_ui.PPDE_SEED_PURPOSE_BOILERPLATE",
    },
    {
        "key": "ppde.stage_map",
        "label": "PPDE stage map boilerplate",
        "type": "PPDE",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_ppde_ui.PPDE_STAGE_MAP_BOILERPLATE",
    },
    {
        "key": "review.route_seed",
        "label": "Review route seed instructions",
        "type": "REVIEW",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_review._build_route_seed_from_intent_llm",
    },
    {
        "key": "review.intent_seed",
        "label": "Review intent seed instructions",
        "type": "REVIEW",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_review._build_intent_seed_from_cko_llm",
    },
    {
        "key": "cko.review.system_block",
        "label": "CKO review system block",
        "type": "REVIEW",
        "source_hint": "GENERATED",
        "builder_ref": "projects.views_review.build_cko_review_system_block",
    },
    {
        "key": "review.execute_actions",
        "label": "Review execute action synthesis instructions",
        "type": "REVIEW",
        "source_hint": "STATIC",
        "builder_ref": "projects.views_review._build_execute_stage_actions_llm",
    },
    {
        "key": "rollup.summary",
        "label": "Rollup summary contract",
        "type": "ROLLUP",
        "source_hint": "STATIC",
        "builder_ref": "chats.services.pinning.rollup_segment",
    },
]
