# Generated by Django 6.0.1 on 2026-02-18 11:15

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_chatworkspace_boundary_profile_json'),
        ('projects', '0049_project_boundary_profile_json_policydocument'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt', models.TextField(blank=True, default='')),
                ('file_id', models.CharField(blank=True, default='', max_length=200)),
                ('mime_type', models.CharField(blank=True, default='image/png', max_length=80)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('image_file', models.FileField(upload_to=uploads.models.generated_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='chats.chatworkspace')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='chats.chatmessage')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='uploads_gen_project_32f6a0_idx'), models.Index(fields=['chat', 'created_at'], name='uploads_gen_chat_id_3ef9ba_idx'), models.Index(fields=['message', 'created_at'], name='uploads_gen_message_a9439a_idx')],
            },
        ),
    ]
